# Generated by Django 5.0.2 on 2024-04-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0005_abouts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abouts',
            new_name='About',
        ),
    ]
