# Generated by Django 5.0.2 on 2024-05-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0010_remove_about_content_af_remove_about_content_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_1', models.ImageField(blank=True, null=True, upload_to='dimg')),
                ('logo_2', models.ImageField(blank=True, null=True, upload_to='dimg')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('job', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('other_url', models.URLField(max_length=255)),
            ],
        ),
    ]
