# Generated by Django 5.0.2 on 2024-05-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0011_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='job',
        ),
    ]
