# Generated by Django 5.0.2 on 2024-05-06 21:50

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0012_remove_setting_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcore.category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blog', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Görüntülenme Sayısı'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='input',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='input',
            name='job',
            field=models.CharField(max_length=100, verbose_name='Meslek'),
        ),
        migrations.AlterField(
            model_name='input',
            name='message',
            field=models.TextField(verbose_name='İleti'),
        ),
        migrations.AlterField(
            model_name='input',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.TextField(verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='keywords',
            field=models.CharField(max_length=255, verbose_name='Anahtar kelimeler'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='Mail adresi'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='other_url',
            field=models.URLField(max_length=255, verbose_name='Resmi web sitesi'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Telefon numarası'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slider', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
    ]
