# Generated by Django 5.0.2 on 2024-05-15 21:54

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('tcore', '0014_input_created_at_input_slug_input_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
