# Generated by Django 5.0.2 on 2024-05-16 17:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0016_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='about', verbose_name='Görsel'),
            preserve_default=False,
        ),
    ]
