# Generated by Django 5.0.2 on 2024-06-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0018_about_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='content',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='title',
        ),
        migrations.AddField(
            model_name='analysis',
            name='input_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='keywords',
            field=models.CharField(default='Anahtar Kelimeler', max_length=200, verbose_name='Anahtar Kelimeler'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='wordcloud',
            field=models.ImageField(default='wordcloud', upload_to='analysis', verbose_name='Kelime Bulutu'),
            preserve_default=False,
        ),
    ]
