# Generated by Django 5.0.2 on 2024-06-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0019_remove_analysis_content_remove_analysis_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='input_id',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='keywords',
            field=models.CharField(max_length=255, verbose_name='Anahtar Kelimeler'),
        ),
    ]
