# Generated by Django 5.0.2 on 2024-06-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0020_remove_analysis_input_id_alter_analysis_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, verbose_name='Anahtar Kelimeler'),
        ),
    ]
