# Generated by Django 5.0.2 on 2024-06-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0021_input_keywords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
